{% set name = "tfv_get_tools" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tfv_get_tools-{{ version }}.tar.gz
  sha256: d51e5641524e990848d476e254bb2b0b67f3a76e17d22548e245df238ddb910b

build:
  entry_points:
    - GetAtmos = tfv_get_tools.cli.atmos_cli:entry
    - GetOcean = tfv_get_tools.cli.ocean_cli:entry
    - GetWave = tfv_get_tools.cli.wave_cli:entry
    - GetTide = tfv_get_tools.cli.tide_cli:entry
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - netcdf4 >=1.6.2
    - tqdm >=4.65.0
    - xarray >=2023.1.0
    - scipy >=1.10.0
    - pyproj >=3.5.0
    - siphon >=0.9
    - cdsapi >=0.7.0
    - copernicusmarine >=1.2.3
    - bottleneck >=1.3.5
    - pytmd >=2.1.5
    - shapely >=2.0.6
    - geopandas >=1.0.1

test:
  imports:
    - tfv_get_tools
  commands:
    - pip check
    - GetAtmos --help
    - GetOcean --help
    - GetWave --help
    - GetTide --help
  requires:
    - pip
    - python {{ python_min }}
  source_files:
    - tests/
    - src/tfv_get_tools

about:
  home: https://gitlab.com/tuflow-user-group/tuflow-fv/data-pre-processing/tfv-get-tools
  summary: Tool for downloading and processing data for TUFLOW FV modelling
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TUFLOW-Support
    - Mitch3007
    - Aewaterhouse
